/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type PostV1Upload200 = {
  [key: string]: string;
};

/**
 * @description Bad Request
 */
export type PostV1Upload400 = {
  [key: string]: string;
};

/**
 * @description Internal Server Error
 */
export type PostV1Upload500 = {
  [key: string]: string;
};

export type PostV1UploadMutationRequest = {
  /**
   * @description Excel (.xlsx) file with contact details
   * @type string, binary
   */
  file: Blob;
};

export type PostV1UploadMutationResponse = PostV1Upload200;

export type PostV1UploadMutation = {
  Response: PostV1Upload200;
  Request: PostV1UploadMutationRequest;
  Errors: PostV1Upload400 | PostV1Upload500;
};
