/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  PostV1UploadMutationRequest,
  PostV1UploadMutationResponse,
  PostV1Upload400,
  PostV1Upload500,
} from "../models/PostV1Upload.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import { buildFormData } from "../.kubb/config.ts";

function getPostV1UploadUrl() {
  const res = { method: "POST", url: `/v1/upload` as const };
  return res;
}

/**
 * @summary Upload an Excel containing contact details
 * {@link /v1/upload}
 */
export async function postV1Upload(
  data: PostV1UploadMutationRequest,
  config: Partial<RequestConfig<PostV1UploadMutationRequest>> & {
    client?: Client;
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const formData = buildFormData(requestData);
  const res = await request<
    PostV1UploadMutationResponse,
    ResponseErrorConfig<PostV1Upload400 | PostV1Upload500>,
    PostV1UploadMutationRequest
  >({
    method: "POST",
    url: getPostV1UploadUrl().url.toString(),
    data: formData as FormData,
    ...requestConfig,
  });
  return res.data;
}
